advancedtelematic/libats

src/main/scala/com/advancedtelematic/libats/codecs/RefinementError.scala, src/main/scala/com/advancedtelematic/libats/data/RefinedUtils.scala
I put it in `data` but if you want it somewhere else I can change.
=> Add RefinedUtils

libats/src/main/scala/com/advancedtelematic/libats/db/SlickExtensions.scala
=> Add helper function to handle empty sequences

build.sbt, libats-metrics-kafka/README.md, libats-metrics-kafka/build.sbt, libats-metrics-kafka/src/main/scala/com/advancedtelematic/metrics/KafkaMetrics.scala, libats-metrics/README.md, libats-metrics/build.sbt, libats-metrics/src/main/resources/reference.conf, libats-metrics/src/main/scala/com/advancedtelematic/metrics/AkkaHttpMetricsSink.scala, libats-metrics/src/main/scala/com/advancedtelematic/metrics/DropwizardMetrics.scala, libats-metrics/src/main/scala/com/advancedtelematic/metrics/InfluxDbMetricsReporter.scala, libats-metrics/src/main/scala/com/advancedtelematic/metrics/NamedMetric.scala
- report kafka metrics to dropwizard metrics
- send dropwizard metrics to InfluxDB
=> Initial version of libats-metrics

libats/src/main/scala/com/advancedtelematic/libats/http/ErrorHandler.scala
Not perfect but I think a step in the right direction
=> use scala style classtag for error classname

libats/build.sbt
=> Bump Slick to v3.2.0

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/DataType.scala, libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala, libats/src/main/scala/com/advancedtelematic/libats/data/ValidationUtils.scala
Add new event `DeviceUpdateReport` that the director will publish for campaigner, and some form of InstallHistory (probably auditor).
I moved some types from director, and libtuf here, and will have PR for them shortly.
=> Add DeviceUpdateReport event

deploy/ci_setup.sh, deploy/cleanup.sh, libats-slick/build.sbt, libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/SlickExtensions.scala, libats-slick/src/test/resources/application.conf, libats-slick/src/test/resources/db/migration/V1__initial_schema.sql, libats-slick/src/test/scala/com/advancedtelematic/libats/slick/db/SlickExtensionsSpec.scala
=> Refactor Slick Extensions, modularize

.gitignore, README.md, libats-slick/README.adoc, libats-slick/src/main/resources/reference.conf, libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/AppMigration.scala, libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/BootMigrations.scala
add support for app level migrations
=> support async migrations

libats-http/src/main/scala/com/advancedtelematic/libats/http/ErrorHandler.scala, libats/src/main/scala/com/advancedtelematic/libats/data/Errors.scala
See https://github.com/advancedtelematic/ota-tuf/pull/103
=> Add support for JsonError

libats-http/src/main/scala/com/advancedtelematic/libats/http/ErrorHandler.scala
Otherwise actors always Escalate instead of Restart
=> Extend from Exception and not Throwable

libats-http/src/main/scala/com/advancedtelematic/libats/http/ErrorHandler.scala
Signed-off-by: Jerry Trieu <jerry.trieu@here.com>
=> Fix handle DecodingFailure in ErrorHandler

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/DataType.scala, libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala
Per suggestion by @koshelev 
Signed-off-by: Jerry Trieu <jerry.trieu@here.com>
=> Redo DeviceUpdateEvent messages

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala
Signed-off-by: Jerry Trieu <jerry.trieu@here.com>
=> Rename DeviceUpdateAvailable to DeviceUpdateAssigned

build.sbt, libats-http/src/main/scala/com/advancedtelematic/libats/http/monitoring/JvmMetrics.scala
Signed-off-by: koshelev <vladimir.koshelev@here.com>
=> Expose JVM cpu and thread metrics

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala, libats/src/main/scala/com/advancedtelematic/libats/data/DataType.scala
Signed-off-by: Jerry Trieu <jerry.trieu@here.com>
=> [OTA-2356] Add DeviceUpdate{Assignment,Cancel}Requested events

libats-messaging/src/test/scala/com/advancedtelematic/libats/messaging/kakfa/MessageListenerActorSpec.scala
Since we were waiting for a promise that was completed on sink
materialization, in can happen that the promise is completed before
the monitor is updated.
This commit changes the test to keep trying until the monitor gets
updated, as there no reliable way to wait for the actor to processed
the result from the stream unless we change the actor the send a
message after updating the monitor.
=> `MessageBusListenerActor` runs the source and receives the result asynchronously **after** the sink is executed.

libats-auth/build.sbt, libats-metrics-finagle/build.sbt, libats-slick/src/test/resources/logback.xml
Versions get checked transitively, so need to bump imported libs here.
=> Bump JWT and typesafe-uri lib version

libats-http-tracing/src/main/scala/com/advancedtelematic/libats/http/tracing/ZipkinRequestTracing.scala
=> Do not tag zipkin trace with auth header

libats-logging/src/main/scala/com/advancedtelematic/libats/logging/JsonEncoder.scala
This allows certain loggers to log valid json as a message and have
that msg processed as valid json by log parsing tools.
=> Add msgIsJson parameter to JsonEncoder

libats-http-tracing/src/main/scala/com/advancedtelematic/libats/http/tracing/ZipkinAkkaHttpClientTracing.scala, libats-http/src/main/scala/com/advancedtelematic/libats/http/logging/RequestLoggingActor.scala
=> Add more info to traces

libats-http/src/main/scala/com/advancedtelematic/libats/http/ServiceHttpClient.scala
Like this we can get more information about the HTTP response, on top of the unmarshalled response. My use-case: I need the response body and a header.
=> Add method to get more information from the Http client

libats-http-tracing/src/main/scala/com/advancedtelematic/libats/http/tracing/ZipkinAkkaHttpClientTracing.scala
=> Handle cases when tracing context is null

libats-logging/src/main/resources/logback-libats.xml, libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/LocalMessageBus.scala, libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/MessageBus.scala, libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/MessageListener.scala, libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/MessageListenerSupport.scala, libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/kafka/KafkaClient.scala
new parameter to continue processing next messages in listener even if
the processing of previous message fails
=> Log debug message immediately after parsing message from bus

build.sbt, deploy/ci_setup.sh, libats-http/src/main/scala/com/advancedtelematic/libats/http/monitoring/JvmMetrics.scala, libats-http/src/main/scala/com/advancedtelematic/libats/http/monitoring/LoggerMetrics.scala, libats-logging/src/main/scala/com/advancedtelematic/libats/logging/JsonEncoder.scala, libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/MessageLike.scala, libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala, libats-metrics-finagle/build.sbt, libats-metrics-prometheus/build.sbt, libats-slick/build.sbt, libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/AppMigration.scala, libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/BootMigrations.scala, libats-slick/src/main/scala/com/advancedtelematic/libats/test/DatabaseSpec.scala, libats-slick/src/test/scala/com/advancedtelematic/libats/slick/db/RunMigrationsSpec.scala, libats/src/main/scala/com/advancedtelematic/libats/codecs/CirceCodecs.scala, project/Versioning.scala, project/build.properties
Clean up some warnings and upgrade:
- Scala
- SBT
- Akka
- Circe
- Flyway
- and others
=> Upgrade versions

.gitlab-ci.yml, project/plugins.sbt
The scan-related pipelines are intended to run as part of the schedule only.
=> Add gitlab CI/CD

.gitlab-ci.yml
Signed-off-by: Vitalii Davydiuk <ext-vitalii.davydiuk@here.com>
=> add test and publish

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala
Add new message CommitManifestUpdated
Sent by treehub when a new image manifest is uploaded
=> Feat/ota 3883/image manifest

libats/src/main/scala/com/advancedtelematic/libats/codecs/JsonDropNullValues.scala
This class is used by multiple projects already, so I am just moving
it here so ti can be reused.
=> Add JsonDropNullValues

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala
Signed-off-by: Jochen Schneider <j.schneider@here.com>
=> Added AktualizrConfigChanged

libats-messaging/build.sbt, libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/kafka/KafkaClient.scala, libats-metrics-kafka/build.sbt
Tested with device-registry.
I built this https://github.com/advancedtelematic/ota-device-registry/pull/150 locally and was able to provision a new device and send updates to it. Also the UI sees the web-events from device-registry, e.g. `DeviceSeen`.
=> [OTA-3845] Upgrade Kafka client.

libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/MessageListener.scala, libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/MessageListenerSupport.scala, libats-metrics-kafka/src/main/scala/com/advancedtelematic/metrics/MonitoredBusListenerSupport.scala, libats-metrics-kafka/src/main/scala/com/advancedtelematic/metrics/PrometheusMessagingMonitor.scala
This is missing from https://github.com/advancedtelematic/libats/pull/137
=> Support setting bus listener in `startListener`

libats-metrics-kafka/src/main/scala/com/advancedtelematic/metrics/PrometheusMessagingMonitor.scala
Actual stream name was used as label name
Changed metric names because prometheus label names and metric names
need to be valid according to some regex
=>  Fix labels in prometheus metrics 
