advancedtelematic/libats

libats-metrics/src/main/resources/reference.conf

Removing them here will force user of the lib to set values in
application.conf. Having default values here is dangerous because
if they are not changed metrics from different services will be
mixed.

Remove serviceName and instanceId from reference.conf

---

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala
libats-messaging-datatype/src/test/scala/com/advancedtelematic/libats/messaging_data/CodecSpec.scala

The event DeviceUpdateReport should have a new field statusCode
which is a result code for the whole device.
For backward compatibility we use a custom decoder that if a statusCode
is not present we interpret all ecus succeding as success (0 OK) otherwise
it is an error (19 GENERAL_ERROR).

[PRO-3533] Update DeviceUpdateReport event

---

libats/src/main/scala/com/advancedtelematic/libats/codecs/CirceRefined.scala

This prevented us from using `_.as[Refined[_, _]] orElse` for example, because an exception was thrown instead of a Left returned.

fix refined codec, again

---

libats-http/src/main/scala/com/advancedtelematic/libats/http/HealthResource.scala
libats-http/src/main/scala/com/advancedtelematic/libats/http/monitoring/HealthCheckHttpClient.scala
libats-http/src/main/scala/com/advancedtelematic/libats/http/monitoring/ServiceHealthCheck.scala
libats-http/src/main/scala/com/advancedtelematic/libats/http/monitoring/VaultHealthCheck.scala
libats-slick/src/main/scala/com/advancedtelematic/libats/slick/monitoring/DbHealthCheck.scala

Support checking dependencies for services and vault
Added to different endpoint and not /health as that would cause all
connected services to reboot if one services fails.
This endpoint can be used by developers and tools to check services
are properly configured and up.

Add /health/dependencies endpoint to health check resource

---

libats-http/src/main/scala/com/advancedtelematic/libats/http/DefaultRejectionHandler.scala
libats/src/main/scala/com/advancedtelematic/libats/codecs/DeserializationException.scala

Avoids giant stacktrace when decoding invalid refined entity

Handle decoding failure on DefaultRejectionHandler

---

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/MessageLike.scala
libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/Messages.scala

Add derive method to MessageLike
This thing caused another hidden bug again, I am removing the derivation by default but keep it there to avoid some code duplication in the codecs... probably would be a good idea to remove it entirely in the future...

Avoid using codec derivation for MessageLike

---

libats-http/src/main/scala/com/advancedtelematic/libats/http/HttpOps.scala

I think it would be nice to add this. Campaigner is using its own implementation of HttpClient, which takes a namespace with the request. If we add this method here I could refactor Campaigner to use this HttpClient and be a bit more consistent across all the microservices.

Extend the HttpClient service to execute requests with namespace.

---

build.sbt
libats-http/src/main/resources/reference.conf
libats-http/src/main/scala/com/advancedtelematic/libats/http/ErrorHandler.scala
libats-http/src/main/scala/com/advancedtelematic/libats/http/LogDirectives.scala
libats-http/src/main/scala/com/advancedtelematic/libats/http/logging/RequestLoggingActor.scala
libats-http/src/main/scala/com/advancedtelematic/libats/http/monitoring/LoggerMetrics.scala
libats-logging/README.md
libats-logging/src/main/resources/application.conf
libats-logging/src/main/resources/logback.xml
libats-logging/src/main/scala/com/advancedtelematic/libats/logging/CirceEncoder.scala

Tested with ota-tuf, pr for tuf follows.
Using a custom Json Logback Encoder as the available encoders (logback-contrib etc) use jackson or some other json library and this way we can just depend on circe. 
Unfortunately I don't know any other way to log the requests with mdc without using this proxy actor. I don't think the risk is big, but it adds that extra layer. I tried a few different approaches like [1], but that doesn't work because akka-http reuses the execution context and also I think it's better to use an extra actor layer than to use an half baked execution context.
[1]: http://yanns.github.io/blog/2014/05/04/slf4j-mapped-diagnostic-context-mdc-with-play-framework/

Add libats-logging, json logging support

---

libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/SlickExtensions.scala
libats/src/main/scala/com/advancedtelematic/libats/data/PaginationResult.scala

When paginating DB results, it would be nice to use `offset` and `limit` consistently. Otherwise it's easy to mix them up and introduce some silly bug. We're always using `offset` first and `limit` second, except in class `PaginationResult`. This PR addresses that.
Also, since just swapping `offset` and `limit` would still compile but break all the services that use pagination without named parameters, I made sure to change the position of the `values` parameter as well. So all services that use this `PaginationResult` will need to update after bumping up libats, but will not break silently.

Use always offset first and limit second as parameters.

---

libats-logging/README.md
libats-logging/src/main/resources/logback-libats.xml

A logback.xml file shouldn't be put into a library since it can't be
extended and it's hard to control which of multiple such files get
loaded from the classpath.

Turn library logback.xml into base config to include in service

---

libats/src/main/scala/com/advancedtelematic/libats/data/DataType.scala

We're starting to use quite a bit result codes and failure codes as `String`, specially in campaigner and device-registry. I thought it would be nice to have some type safety by introducing these types.

Create ResultCode and FailureCode types for type safety

---

libats/src/main/scala/com/advancedtelematic/libats/data/DataType.scala

We are going to use `DeviceOemId` in campaigner for the CSV export. We might as well move it to libats.

[OTA-2308] Move DeviceOemId from device-registry

---

libats/src/main/scala/com/advancedtelematic/libats/data/DataType.scala

We decided this class should keep on living in device-registry after all, so let's remove it from here.

Don't expose DeviceOemId as a class to other services

---

libats-messaging-datatype/src/main/scala/com/advancedtelematic/libats/messaging_datatype/DataType.scala
libats/src/main/scala/com/advancedtelematic/libats/data/DataType.scala

Let's use this `ResultCode` and `ResultDescription` value classes in the `InstallationResult` to gain some type safety and readability? See #97.

Use ResultCode in InstallationResult for type safety

---

build.sbt
libats-metrics-akka/src/main/scala/com/advancedtelematic/metrics/AkkaHttpMetricsSink.scala

One particular endpoint in device-registry is failing for me, apparently because the Akka version in libats is older than the one in device-registry. This fixes that, though we might have to update the Akka version in other services.

Bump Akka and AkkaHttp to the latest version

---

libats-slick/README.adoc
libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/BootMigrations.scala
libats-slick/src/main/scala/com/advancedtelematic/libats/test/DatabaseSpec.scala
libats-slick/src/test/resources/logback-test.xml
libats-slick/src/test/resources/logback.xml
libats-slick/src/test/scala/com/advancedtelematic/libats/slick/db/RunMigrationsSpec.scala

Remove `AsyncMigrations`. This is not used by any project and can
anyway be used with `ASYNC_MIGRATE=true` instead.

Add main class to run migrations

---

libats-slick/src/main/resources/reference.conf
libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/BootMigrations.scala
libats-slick/src/test/scala/com/advancedtelematic/libats/slick/db/RunMigrationsSpec.scala

I think this is all we need for OTA-3457:
- The older version will not detect pending migrations, these are
calculated from source, so the old version would continue running.
- The new version deployment would fail as flyway would detect
pending migrations

Add trait that forces an app to quit if schema has pending migrations

---

libats-slick/src/main/resources/reference.conf
libats-slick/src/main/scala/com/advancedtelematic/libats/slick/db/BootMigrations.scala
libats-slick/src/test/scala/com/advancedtelematic/libats/slick/db/RunMigrationsSpec.scala

Up until version 5.0.0 Flyway used to store the migration historical info in a table called `schema_version`. From version 5 the table is called `flyway_schema_history`. Version 6 drops the fallback mechanism that allowed to still user the old name for the table. We want to migrate from 4 to 6 but don't want to go through the hassle of renaming the old schema table.
Related:
- https://github.com/flyway/flyway/issues/2010
- https://flywaydb.org/documentation/releaseNotes#5.0.0

Make the Flyway schema table configurable.

---

libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/daemon/MessageBusListenerActor.scala
libats-metrics-kafka/src/main/scala/com/advancedtelematic/metrics/MonitoredBusListenerSupport.scala
libats-metrics-kafka/src/main/scala/com/advancedtelematic/metrics/PrometheusMessagingMonitor.scala

prometheus java client requires us to use a static val to share counters.
See https://github.com/prometheus/client_java#registering-metrics
Fix bug when failure that causes subscriber to die
even when `monitorSafe` is used.
This is a rather subtle and hard to track bug.
`monitor.onProcessed` returns a future and `monitorSafe` recovers from
that future. The problem is `monitor.onProcessed` can fail **before**
actually creating the future, so `monitorOnProcessed` will fail before
it returns a future that `monitorSafe` can recover from, so this was
not safe at all.
Changed it to wrap `onProcessed` into a try to really make sure the
listener does not die if something goes wrong with `monitor`.

Use static val for prometheus counters

---

libats-messaging/src/main/scala/com/advancedtelematic/libats/messaging/MessageListener.scala
libats/src/main/scala/com/advancedtelematic/libats/data/UUIDKey.scala

We currently catch a failed future when MsgOperation returns a failed
future, but if MsgOperation cannot create a valid future, successful or
failed, we don't catch that and propagate the exception up.
This change catches exceptions when MsgOperation fails before it can
produce a valid future.
Fix decoding errors when decoding UUID
If `String` is not a valid UUID the decoders would throw an
`IllegalArgumentException` rather than a failed decoder. This makes UUIDKey
decoders use the default circe decoders for UUID which handle those
exceptions.

Catch exceptions when MsgOperation fails to create a future

---

libats/src/main/scala/com/advancedtelematic/libats/data/DataType.scala

This is needed to give a correlation id to auto updates.
director-lite always requires a correlationId. auto updates dont't
have an mtu or a campaign associated, so we need a new correlation id.
director v1 allows auto updates without correlation id

Add AutoUpdateId for CorrelationId

---

libats-http/src/main/scala/com/advancedtelematic/libats/http/ErrorHandler.scala
libats-http/src/test/scala/com/advancedtelematic/libats/http/ErrorHandlerSpec.scala

Currently the ErrorRepresentation only includes the message like
"Attempt to decode value on failed cursor", now it includes also the
history which led to the operation that failed.

Error representation for DecodingFailure should include history

---

libats-slick/src/main/scala/com/advancedtelematic/libats/test/InstantMatchers.scala
libats-slick/src/test/scala/com/advancedtelematic/libats/slick/db/InstantMatchersSpec.scala

Enables syntax like `ts0 is after(ts1)`
Adding this to `libats-slick` because this is the only package that already has a class that is used in tests in downstream projects (`DatabaseSpec`) and I don't think this warrants a separate module

Add `after` and `before` for `java.time.Instant` in scalatest

---

libats-http/src/main/scala/com/advancedtelematic/libats/http/DefaultRejectionHandler.scala

Also keep history in message from default rejection handler. Tested locally with the API provider.
Signed-off-by: Jochen Schneider <j.schneider@here.com>

Default rejection handler: show the JSON decoding history (path)
